new-session
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g history-limit 9999
set -g mode-keys vi
set -g status-right 'pid:#{pid} #(date +"%a %b %d %I:%M")'
set-option pane-active-border-bg green
set-option pane-active-border-fg green
set-option pane-border-fg green
set-option status-left "#W:"
set-option status-left-bg black
set-option status-left-fg green
set-option display-time 5000
set-option main-pane-height 34
set-option main-pane-width 100

source ~/sc-dev/wide.tmux
source ~/sc-dev/twin.tmux
source ~/sc-dev/twin.tmux

next-window
kill-window
next-window

