new-session
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key Left select-layout even-horizontal
bind-key Right select-layout main-vertical
bind-key Up select-layout even-vertical
bind-key Down select-layout main-horizontal
set -g history-limit 9999
set -g mode-keys vi
set -g status-right 'pid:#{pid} #(date +"%a %b %d %I:%M")'
set-option status-left "#W:"
set-option display-time 5000
set-option main-pane-height 40
set-option main-pane-width 100

source ~/sc-dev/twin.tmux
source ~/sc-dev/twin.tmux
source ~/sc-dev/twin.tmux

next-window
kill-window
next-window

