new-session
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
bind-key -n DoubleClick1Pane select-pane \; copy-mode \; send-keys -X select-word \; send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -n TripleClick1Pane select-pane \; copy-mode \; send-keys -X select-line \; send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R
set -g history-limit 9999
set -g mode-keys vi
set -g status-right 'pid:#{pid} #(date +"%a %b %d %I:%M")'
set -g status-style "bg=color46,fg=colour16"
set-option status-left "#W:"
set-option display-time 5000
set-option main-pane-height 40
set-option main-pane-width 100

source ~/sc-dev/mac/twin.tmux
source ~/sc-dev/mac/twin.tmux
source ~/sc-dev/mac/twin.tmux

next-window
kill-window
next-window

