#!/bin/bash
DIR="$(dirname "$0")"
source $DIR/console-defs

TIMESTAMP BEGIN

INFO initializing home directory...
cd ~
ln -sf ~/sc-dev/mac/bin ~/bin
ln -sf ~/sc-dev/vimrc ~/.vimrc
ln -sf ~/sc-dev/mac/tmux.conf ~/.tmux.conf
ln -sf ~/sc-dev/indent.pro ~/.indent.pro
ln -sf ~/sc-dev/astyle.rc ~/.astylerc
LOCAL=`realpath $DIR/../../local`
if [ -d $LOCAL ]; then
  DEBUG "Folder $LOCAL already exists"
else
  mkdir $LOCAL
  INFO "Created folder: $LOCAL"
fi


INFO setting up git global configuration
git config --global user.email "karl@firepick.org"
git config --global user.name "Karl Lew"
git config --global push.default simple
brew install -q git-lfs

if [ -e .bashrc ]; then
    cmp .bashrc sc-dev/mac/.bashrc
    RC=$?; if [ "$RC" != "0" ]; then
        mv -f .bashrc .bashrc.old
    fi
fi
ln -sf ~/sc-dev/mac/.bashrc .bashrc

INFO installing console tools
brew install -q vim
brew install -q tmux

INFO installing performance tools
brew install -q asitop
brew install -q btop
brew install -q nvtop
brew install -q iftop
brew install -q htop

INFO installing AI tools
brew install -q ollama
brew install -q --cask visual-studio-code
ollama pull nomic-embed-text

INFO install AV tools
brew install -q ffmpeg

type nvm 2> /dev/null
RC=$?
INFO nvm $RC
if [ $RC -ne 0 ]; then
  INFO Installing nvm
  curl -o $LOCAL/nvm-install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh
  chmod +x $LOCAL/nvm-install.sh
  RC=asdf
  $LOCAL/nvm-install.sh; CHKRC
  echo RC$RC
else
  INFO nvm `nvm --version`
  INFO nodejs `node --version`
fi

TIMESTAMP END
